### ISSUE TITLE
DISCON.dll can not be loaded.

### ISSUE THREAD

**Issue by dnrgus2581** [tashuri/20MW-wind-turbine-model#1]
whenever I try to run the  FAST_7u.fst with the FAST_V601_EC.exe, command window say below

-----------------------------------------------------------------------------------------------------------
The DLL DISCON.dll could not be loaded.

 Aborting FAST.

**Comment by tashuri** [comment]
Please recompile the discon.f90 file with a Fortran compiler natively on your machine. Please email me at turaj dot ashuri at gmail dot com for technical help.
